language: node_js

node_js:
- "10"

install:
- travis_retry npm ci
- npm run build

script:
- npm run test

deploy:
    provider: script
    skip_cleanup: true # So it keeps npm_modules
    script: npx semantic-release
    on:
        branch: master
