language: node_js

node_js:
- "10"

install:
- travis_retry npm ci
- npm run build

script:
- npm run test
- npm run doc

deploy:
    provider: script
    skip_cleanup: true # So it keeps npm_modules
    script:
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"
    - git remote set-url origin https://$GH_TOKEN@https://github.com/Slowki/react-golden-layout
    - npx semantic-release
    on:
        branch: master
